/* Design reminder: copy remains terse, verifiable and consultant-grade in all three languages. */
import type { Language } from "@/contexts/LanguageContext";

type TranslationMap = Record<string, string>;

const english: TranslationMap = {
  "框架原则": "Framework principle", "价值主张必须可追溯到痛点、能力、经营变量、KPI 与证据状态。": "Every value claim must trace back to a pain point, capability, operating variable, KPI, and evidence status.",
  "从运输信号，建立": "Turn transport signals into", "可验证的": "verifiable", "价值档案。": "value evidence.", "以 OTM 能力、客户数据、ROI 方法和决策叙事构成一条有证据、可回溯、可组装的价值路径。": "Connect OTM capabilities, customer data, ROI methods, and a decision narrative into an evidence-led, traceable, composable value path.",
  "痛点": "Pain point", "能力": "Capability", "变量": "Variable", "价值": "Value", "检索价值档案": "Browse value archive", "验证当前证据": "Validate current evidence", "已量化的首期价值闭环": "Quantified first-wave value loop",
  "八个领域，一张可以复用的价值地图。": "Eight domains. One reusable value map.", "一级分类按价值实现路径而非产品菜单构建。每个领域都可展开为独立的诊断、数据、ROI 和叙事模块。": "The taxonomy follows value realization paths—not a product menu. Each domain expands into a diagnostic, data, ROI, and narrative module.",
  "已量化": "Quantified", "待量化": "Pending quantification", "方向性": "Directional", "可选扩展": "Optional extension", "客户痛点": "Customer pain point", "OTM 能力": "OTM capability", "经营变量": "Operating variable", "价值判断": "Value judgment", "支出泄漏": "Spend leakage", "成本与利用率": "Cost & utilization", "条款与运力": "Terms & capacity", "生产率": "Productivity", "服务与响应": "Service & response", "资产利用": "Asset utilization", "结构性改善": "Structural improvement", "风险与外部性": "Risk & externalities",
  "一次维护，三种决策视图。": "One evidence base. Three decision views.", "不从头建立客户版与内部版。每张 driver 卡都是唯一事实源，只按读者改变展示深度。": "Do not rebuild internal and customer versions from scratch. Each driver card is one source of truth; only the depth changes by audience.",
  "内部工作台": "Internal workspace", "客户 Value Assessment": "Customer Value Assessment", "让每个主张都能回到数据。": "Make every claim return to data.", "为售前、咨询与财务团队保留方法论、公式准备度、数据血缘与去重规则。这里不是客户交付物，而是受控的价值工作底稿。": "Retain methodology, formula readiness, data lineage, and de-duplication rules for presales, consulting, and finance. This is a controlled value working paper—not a customer deliverable.",
  "ROI 公式家族": "ROI formula family", "已定义；需逐项验证假设与去重逻辑": "Defined; validate assumptions and de-duplication case by case", "数据质量门槛": "Data quality threshold", "发票、费率、运输事件必须可匹配": "Invoices, rates, and transport events must be matchable", "范围与产品边界": "Scope & product boundary", "OTM 与更广 Oracle 能力独立标识": "OTM and broader Oracle capabilities are separately identified", "批准状态": "Approval status", "首期仅纳入已确认的 US 价值闭环": "The first wave includes only the confirmed US value loop",
  "先看清机会，再讨论数字。": "See the opportunity before debating the numbers.", "以诊断问题、KPI 和所需数据帮助客户共同识别价值；不展示内部方法论，也不把尚未验证的机会伪装成已承诺收益。": "Use diagnostic questions, KPIs, and required data to identify value jointly; do not reveal internal methods or present unverified opportunities as committed benefits.", "客户触发条件": "Customer triggers", "哪些费率、账单或状态信号正在造成损失？": "Which rate, invoice, or status signals are creating loss?", "可验证的机会": "Verifiable opportunity", "先确认基线、范围和可用证据": "Confirm baseline, scope, and available evidence first", "所需数据类别": "Required data classes", "运输、账单、费率、里程碑和服务事件": "Transport, invoices, rates, milestones, and service events", "证据状态": "Evidence status", "已量化 / 有证据待量化 / 方向性": "Quantified / evidenced but pending / directional",
  "把已证实的发现转成决策。": "Turn proven findings into decisions.", "面向预算与优先级决策者，呈现已选 driver 的量化价值、关键假设、实施依赖和分期路线图；未验证的内容保留在扩展层。": "For budget and priority decision-makers, present quantified value, key assumptions, implementation dependencies, and a phased roadmap; retain unverified items in the extension layer.", "核心价值": "Core value", "US freight audit + visibility 的直接、去重 ROI": "Direct, de-duplicated ROI from US freight audit + visibility", "关键假设": "Key assumptions", "基线、适用费率、可实现性与责任归属": "Baseline, applicable rates, realizability, and ownership", "分期范围": "Phased scope", "首期验证 US；Europe 进入独立证据阶段": "Validate US first; move Europe into an independent evidence phase", "下一决策": "Next decision", "用验证门槛控制后续产品与区域扩展": "Use validation gates to control product and regional expansion",
  "Value Assessment 是共同诊断，不是预设结论。": "Value Assessment is a joint diagnosis—not a predetermined conclusion.", "从客户可以回答的问题开始，逐步确认基线、数据和证据状态；只有通过数据门槛的 driver 才进入 ROI 计算和预算叙事。": "Start with questions the customer can answer, then confirm baselines, data, and evidence status. Only drivers that clear data thresholds enter the ROI calculation and budget narrative.", "运输支出是否能与合同费率和运输事件逐项匹配？": "Can transportation spend be matched line by line to contracted rates and transport events?", "异常和延迟被识别时，是否还来得及采取纠正行动？": "When an exception or delay is detected, is there still time to take corrective action?", "哪些 KPI 已有可信基线，哪些仍需作为方向性价值？": "Which KPIs have credible baselines, and which remain directional value?", "US 证据与 Europe 证据是否被明确隔离，避免错误外推？": "Are US and Europe evidence clearly separated to avoid invalid extrapolation?",
  "用证据状态管理范围，而不是用全部能力堆叠范围。": "Manage scope through evidence status—not by stacking every capability.", "每一个新增诉求必须进入既定 driver 卡，并明确其证据层级、数据条件和决策门槛。": "Every added request must enter an existing driver card and state its evidence tier, data requirements, and decision gate.", "已验证的核心价值": "Validated core value", "US freight audit 与 visibility 的直接价值闭环；使用基线、范围、去重规则和敏感性表达。": "A direct value loop from US freight audit and visibility; express it with baselines, scope, de-duplication rules, and sensitivities.", "有证据、待量化的扩展价值": "Evidenced, pending-quantification extension", "Europe 的相同 driver 或相邻机会；说明诊断和验证计划，不承诺具体金额。": "The same drivers or adjacent opportunities in Europe; state a diagnostic and validation plan without committing an amount.", "战略路线图选项": "Strategic roadmap options", "网络建模、车队、可持续性或更广 Oracle 能力；保留给独立的范围确认和商业案例。": "Network modeling, fleet, sustainability, or broader Oracle capabilities; reserve them for separate scope confirmation and a business case.", "先确认数据成熟度，再进入 ROI 计算。": "Confirm data maturity before entering ROI calculation.", "OTM Value Driver Library 将每个价值主张锚定到痛点、能力、经营变量、KPI 与可审计的证据状态。": "OTM Value Driver Library anchors each value claim to a pain point, capability, operating variable, KPI, and auditable evidence status.",
  "运输规划与 Cost-to-Serve 优化": "Transportation Planning & Cost-to-Serve", "以方式、路线、服务等级与合并逻辑降低每单位运输成本。": "Lower transport cost per unit through mode, route, service-level, and consolidation choices.", "模式 / 路径选择 · 订单合并 · 加急管控": "Mode / route selection · order consolidation · expedite control", "每票运输成本": "Transport cost per shipment", "装载率": "Load factor", "加急运费": "Expedite spend", "订单、费率、路线、服务等级和历史运量": "Orders, rates, routes, service levels, and historic volume", "用于说明客户是否在每次运输中作出合适的成本—服务权衡。": "Shows whether the customer makes the right cost-service trade-off on every move.",
  "承运商采购、商业条款与运力管理": "Carrier Sourcing, Commercial Terms & Capacity", "将竞争性运价、可靠运力与承运商履约放入同一商业控制面。": "Bring competitive rates, reliable capacity, and carrier performance into one commercial control plane.", "电子招标 · 费率治理 · 分配合规": "Digital tendering · rate governance · allocation compliance", "合同价差": "Contract variance", "主承运商使用率": "Primary-carrier utilization", "接受率": "Acceptance rate", "合同、tender、实际运价、承运商绩效": "Contracts, tenders, actual rates, and carrier performance", "用于把 carrier 管理从关系管理转换为可观察的经济表现。": "Turns carrier management from relationship management into observable economic performance.",
  "运输执行与作业自动化": "Transportation Execution & Automation", "减少人工触点、重复沟通与操作偏差，让团队规模随运量而不是随人头增长。": "Reduce manual touches, repetitive communication, and operating variance so team scale follows volume—not headcount.", "自动建运单 · 承运商协同 · 例外工作流": "Automated shipment creation · carrier collaboration · exception workflows", "每票处理分钟": "Minutes per shipment", "自动化率": "Automation rate", "返工率": "Rework rate", "流程日志、作业量、FTE、错误与返工记录": "Process logs, activity volume, FTEs, and error/rework records", "用于建立业务效率而非单纯系统功能的价值基线。": "Establishes a value baseline for business efficiency—not system features alone.",
  "货运支出完整性、审计与财务结算": "Freight Spend Integrity, Audit & Settlement", "识别错付、重复账单和费率偏差，并把争议、结算与预提纳入闭环。": "Identify overpayments, duplicate invoices, and rate variances, then bring disputes, settlement, and accruals into one closed loop.", "三方匹配 · 异常收费 · 争议闭环": "Three-way match · anomalous charges · dispute closure", "审计命中金额": "Audit recovery", "错付率": "Overpayment rate", "账单一次通过率": "First-pass invoice rate", "发票、合同费率、运输事件、争议与付款记录": "Invoices, contracted rates, transport events, disputes, and payment records", "首期硬 ROI 的核心：只把可验证、可去重的回收和避免支出计入。": "Core first-wave hard ROI: include only recoveries and avoided spend that are verifiable and de-duplicated.",
  "运输可视化、例外响应与服务保障": "Transportation Visibility, Exception Response & Service Assurance", "更早看见风险、编排响应并提升承诺交付的可靠性。": "See risk earlier, orchestrate response, and improve committed-delivery reliability.", "里程碑 · ETA · 延迟预警 · 状态沟通": "Milestones · ETA · delay alerts · status communication", "例外关闭时间": "Exception closure time", "加急补救成本": "Expedite recovery cost", "里程碑、ETA、延迟事件、客服与补救成本": "Milestones, ETA, delay events, customer service, and recovery cost", "与 freight audit 组合形成“检测—决策—纠正—结算”的可验证闭环。": "Combined with freight audit, creates a verifiable detect-decide-correct-settle loop.",
  "自有车队、设备与资产生产率": "Private Fleet, Equipment & Asset Productivity", "在自有和外包运力之间优化车辆、司机、设备与回程资源。": "Optimize vehicles, drivers, equipment, and backhaul resources across private and outsourced capacity.", "自有/外包平衡 · 设备调配 · 空驶控制": "Private / outsourced balance · equipment positioning · empty-mile control", "空驶率": "Empty-mile rate", "自有车队利用率": "Private-fleet utilization", "设备周转": "Equipment turns", "车队状态、司机、设备、外包成本和线路": "Fleet status, drivers, equipment, outsourced costs, and lanes", "仅在客户拥有或混合使用车队时进入正式价值范围。": "Enter formal value scope only when the customer owns or uses a hybrid fleet.",
  "网络决策、绩效洞察与持续改善": "Network Decisions, Performance Insight & Continuous Improvement", "用真实运营数据进行情景建模，把单次优化变成可持续的治理机制。": "Use real operating data for scenario modeling and turn one-off optimization into a sustainable governance mechanism.", "情景建模 · 车道治理 · 根因洞察": "Scenario modeling · lane governance · root-cause insight", "网络 Cost-to-Serve": "Network Cost-to-Serve", "计划/实际偏差": "Plan / actual variance", "兑现率": "Realization rate", "历史运输、网络约束、成本、服务与情景参数": "Historical movements, network constraints, cost, service, and scenario parameters", "作为已验证执行价值之后的结构性扩展，而不是首期 ROI 的填充项。": "A structural extension after validated execution value—not a filler for first-wave ROI.",
  "合规、碳排与韧性": "Compliance, Carbon & Resilience", "当客户议程覆盖跨境、ESG 或供应链风险时，才作为可选扩展领域。": "Use as an optional extension only when the customer agenda includes cross-border, ESG, or supply-chain risk.", "排放分析 · 中断情景 · 文件完备性": "Emissions analysis · disruption scenarios · document completeness", "CO₂e / 运量": "CO₂e / volume", "合规事件": "Compliance events", "恢复时间": "Recovery time", "排放、法规、事件、路线与业务连续性数据": "Emissions, regulations, events, routes, and business-continuity data", "需明确产品边界；跨境贸易深度合规不应默认归因于 OTM。": "Clarify product boundaries; deep cross-border trade compliance should not be attributed to OTM by default.",
};

const spanish: TranslationMap = {
  "框架原则": "Principio del marco", "价值主张必须可追溯到痛点、能力、经营变量、KPI 与证据状态。": "Toda propuesta de valor debe rastrearse a un problema, una capacidad, una variable operativa, un KPI y un estado de evidencia.",
  "从运输信号，建立": "Convierta las señales de transporte en", "可验证的": "valor verificable", "价值档案。": ".", "以 OTM 能力、客户数据、ROI 方法和决策叙事构成一条有证据、可回溯、可组装的价值路径。": "Conecte capacidades de OTM, datos del cliente, métodos de ROI y una narrativa de decisión en una ruta de valor basada en evidencia, trazable y modular.",
  "痛点": "Problema", "能力": "Capacidad", "变量": "Variable", "价值": "Valor", "检索价值档案": "Explorar archivo de valor", "验证当前证据": "Validar evidencia actual", "已量化的首期价值闭环": "Ciclo de valor inicial cuantificado",
  "八个领域，一张可以复用的价值地图。": "Ocho dominios. Un mapa de valor reutilizable.", "一级分类按价值实现路径而非产品菜单构建。每个领域都可展开为独立的诊断、数据、ROI 和叙事模块。": "La taxonomía sigue rutas de realización de valor, no un menú de producto. Cada dominio se despliega en módulos de diagnóstico, datos, ROI y narrativa.",
  "已量化": "Cuantificado", "待量化": "Pendiente de cuantificar", "方向性": "Direccional", "可选扩展": "Extensión opcional", "客户痛点": "Problema del cliente", "OTM 能力": "Capacidad de OTM", "经营变量": "Variable operativa", "价值判断": "Juicio de valor", "支出泄漏": "Fuga de gasto", "成本与利用率": "Coste y utilización", "条款与运力": "Términos y capacidad", "生产率": "Productividad", "服务与响应": "Servicio y respuesta", "资产利用": "Uso de activos", "结构性改善": "Mejora estructural", "风险与外部性": "Riesgo y externalidades",
  "一次维护，三种决策视图。": "Una base de evidencia. Tres vistas de decisión.", "不从头建立客户版与内部版。每张 driver 卡都是唯一事实源，只按读者改变展示深度。": "No reconstruya desde cero las versiones internas y para clientes. Cada ficha de driver es una única fuente de verdad; solo cambia la profundidad según el público.",
  "内部工作台": "Espacio interno", "客户 Value Assessment": "Evaluación de valor del cliente", "让每个主张都能回到数据。": "Haga que cada afirmación vuelva a los datos.", "为售前、咨询与财务团队保留方法论、公式准备度、数据血缘与去重规则。这里不是客户交付物，而是受控的价值工作底稿。": "Conserve metodología, preparación de fórmulas, linaje de datos y reglas de deduplicación para preventa, consultoría y finanzas. Es un documento de trabajo controlado, no un entregable para el cliente.",
  "ROI 公式家族": "Familia de fórmulas ROI", "已定义；需逐项验证假设与去重逻辑": "Definida; validar supuestos y deduplicación caso por caso", "数据质量门槛": "Umbral de calidad de datos", "发票、费率、运输事件必须可匹配": "Facturas, tarifas y eventos de transporte deben poder conciliarse", "范围与产品边界": "Alcance y límite del producto", "OTM 与更广 Oracle 能力独立标识": "OTM y capacidades más amplias de Oracle se identifican por separado", "批准状态": "Estado de aprobación", "首期仅纳入已确认的 US 价值闭环": "La primera fase incluye solo el ciclo de valor de EE. UU. confirmado",
  "先看清机会，再讨论数字。": "Comprenda la oportunidad antes de discutir cifras.", "以诊断问题、KPI 和所需数据帮助客户共同识别价值；不展示内部方法论，也不把尚未验证的机会伪装成已承诺收益。": "Use preguntas diagnósticas, KPI y datos requeridos para identificar valor en conjunto; no exponga métodos internos ni presente oportunidades no verificadas como beneficios comprometidos.", "客户触发条件": "Factores desencadenantes", "哪些费率、账单或状态信号正在造成损失？": "¿Qué señales de tarifa, factura o estado están causando pérdidas?", "可验证的机会": "Oportunidad verificable", "先确认基线、范围和可用证据": "Primero confirme línea base, alcance y evidencia disponible", "所需数据类别": "Clases de datos requeridas", "运输、账单、费率、里程碑和服务事件": "Transporte, facturas, tarifas, hitos y eventos de servicio", "证据状态": "Estado de evidencia", "已量化 / 有证据待量化 / 方向性": "Cuantificado / con evidencia pendiente / direccional",
  "把已证实的发现转成决策。": "Convierta hallazgos probados en decisiones.", "面向预算与优先级决策者，呈现已选 driver 的量化价值、关键假设、实施依赖和分期路线图；未验证的内容保留在扩展层。": "Para quienes deciden presupuesto y prioridades, presente valor cuantificado, supuestos clave, dependencias de implementación y una hoja de ruta por fases; mantenga lo no verificado en la capa de extensión.", "核心价值": "Valor principal", "US freight audit + visibility 的直接、去重 ROI": "ROI directo y sin duplicación de auditoría de fletes + visibilidad en EE. UU.", "关键假设": "Supuestos clave", "基线、适用费率、可实现性与责任归属": "Línea base, tarifas aplicables, realizabilidad y responsabilidad", "分期范围": "Alcance por fases", "首期验证 US；Europe 进入独立证据阶段": "Validar EE. UU. primero; Europa entra en una fase de evidencia independiente", "下一决策": "Siguiente decisión", "用验证门槛控制后续产品与区域扩展": "Use puertas de validación para controlar la expansión de producto y región",
  "Value Assessment 是共同诊断，不是预设结论。": "La evaluación de valor es un diagnóstico conjunto, no una conclusión predeterminada.", "从客户可以回答的问题开始，逐步确认基线、数据和证据状态；只有通过数据门槛的 driver 才进入 ROI 计算和预算叙事。": "Comience con preguntas que el cliente pueda responder; después confirme líneas base, datos y estado de evidencia. Solo los drivers que superen el umbral de datos entran al cálculo ROI y a la narrativa presupuestaria.", "运输支出是否能与合同费率和运输事件逐项匹配？": "¿Se puede conciliar cada gasto de transporte con las tarifas contratadas y los eventos de transporte?", "异常和延迟被识别时，是否还来得及采取纠正行动？": "Cuando se identifica una excepción o demora, ¿aún hay tiempo para actuar?", "哪些 KPI 已有可信基线，哪些仍需作为方向性价值？": "¿Qué KPI tienen una línea base confiable y cuáles siguen siendo valor direccional?", "US 证据与 Europe 证据是否被明确隔离，避免错误外推？": "¿La evidencia de EE. UU. y Europa está separada para evitar extrapolaciones inválidas?",
  "用证据状态管理范围，而不是用全部能力堆叠范围。": "Gestione el alcance mediante estado de evidencia, no apilando todas las capacidades.", "每一个新增诉求必须进入既定 driver 卡，并明确其证据层级、数据条件和决策门槛。": "Cada solicitud nueva debe entrar en una ficha de driver existente e indicar su nivel de evidencia, requisitos de datos y puerta de decisión.", "已验证的核心价值": "Valor central validado", "US freight audit 与 visibility 的直接价值闭环；使用基线、范围、去重规则和敏感性表达。": "Ciclo de valor directo de auditoría de fletes y visibilidad en EE. UU.; expréselo con líneas base, alcance, deduplicación y sensibilidades.", "有证据、待量化的扩展价值": "Extensión con evidencia, pendiente de cuantificar", "Europe 的相同 driver 或相邻机会；说明诊断和验证计划，不承诺具体金额。": "Los mismos drivers u oportunidades adyacentes en Europa; describa el plan de diagnóstico y validación sin comprometer un importe.", "战略路线图选项": "Opciones de hoja de ruta estratégica", "网络建模、车队、可持续性或更广 Oracle 能力；保留给独立的范围确认和商业案例。": "Modelado de red, flota, sostenibilidad o capacidades más amplias de Oracle; resérvelos para una confirmación de alcance y un caso de negocio independiente.", "先确认数据成熟度，再进入 ROI 计算。": "Confirme la madurez de los datos antes de entrar al cálculo ROI.", "OTM Value Driver Library 将每个价值主张锚定到痛点、能力、经营变量、KPI 与可审计的证据状态。": "OTM Value Driver Library ancla cada propuesta de valor a un problema, una capacidad, una variable operativa, un KPI y un estado de evidencia auditable.",
  "运输规划与 Cost-to-Serve 优化": "Planificación de transporte y Cost-to-Serve", "以方式、路线、服务等级与合并逻辑降低每单位运输成本。": "Reduzca el coste de transporte por unidad mediante decisiones de modo, ruta, nivel de servicio y consolidación.", "模式 / 路径选择 · 订单合并 · 加急管控": "Selección de modo/ruta · consolidación de pedidos · control de urgencias", "每票运输成本": "Coste por envío", "装载率": "Factor de carga", "加急运费": "Gasto urgente", "订单、费率、路线、服务等级和历史运量": "Pedidos, tarifas, rutas, niveles de servicio y volumen histórico", "用于说明客户是否在每次运输中作出合适的成本—服务权衡。": "Muestra si el cliente toma la decisión adecuada entre coste y servicio en cada movimiento.",
  "承运商采购、商业条款与运力管理": "Sourcing de transportistas, términos comerciales y capacidad", "将竞争性运价、可靠运力与承运商履约放入同一商业控制面。": "Integre tarifas competitivas, capacidad confiable y desempeño del transportista en un único plano de control comercial.", "电子招标 · 费率治理 · 分配合规": "Licitación digital · gobierno de tarifas · cumplimiento de asignación", "合同价差": "Variación contractual", "主承运商使用率": "Uso del transportista principal", "接受率": "Tasa de aceptación", "合同、tender、实际运价、承运商绩效": "Contratos, licitaciones, tarifas reales y desempeño del transportista", "用于把 carrier 管理从关系管理转换为可观察的经济表现。": "Convierte la gestión de transportistas de gestión de relaciones a desempeño económico observable.",
  "运输执行与作业自动化": "Ejecución de transporte y automatización", "减少人工触点、重复沟通与操作偏差，让团队规模随运量而不是随人头增长。": "Reduzca toques manuales, comunicación repetitiva y variación operativa para que el equipo escale con volumen, no con plantilla.", "自动建运单 · 承运商协同 · 例外工作流": "Creación automática de envíos · colaboración con transportistas · flujos de excepción", "每票处理分钟": "Minutos por envío", "自动化率": "Tasa de automatización", "返工率": "Tasa de reproceso", "流程日志、作业量、FTE、错误与返工记录": "Registros de proceso, volumen de trabajo, FTE y registros de errores/reproceso", "用于建立业务效率而非单纯系统功能的价值基线。": "Establece una línea base de eficiencia operativa, no solo de funciones del sistema.",
  "货运支出完整性、审计与财务结算": "Integridad del gasto de flete, auditoría y liquidación", "识别错付、重复账单和费率偏差，并把争议、结算与预提纳入闭环。": "Identifique sobrepagos, facturas duplicadas y variaciones de tarifa, e integre disputas, liquidación y devengos en un ciclo cerrado.", "三方匹配 · 异常收费 · 争议闭环": "Conciliación a tres bandas · cargos anómalos · cierre de disputas", "审计命中金额": "Recuperación de auditoría", "错付率": "Tasa de sobrepago", "账单一次通过率": "Tasa de factura a la primera", "发票、合同费率、运输事件、争议与付款记录": "Facturas, tarifas contratadas, eventos de transporte, disputas y pagos", "首期硬 ROI 的核心：只把可验证、可去重的回收和避免支出计入。": "Núcleo del ROI duro inicial: incluya solo recuperaciones y gasto evitado verificables y sin duplicación.",
  "运输可视化、例外响应与服务保障": "Visibilidad de transporte, respuesta a excepciones y garantía de servicio", "更早看见风险、编排响应并提升承诺交付的可靠性。": "Vea el riesgo antes, coordine la respuesta y mejore la confiabilidad de entrega comprometida.", "里程碑 · ETA · 延迟预警 · 状态沟通": "Hitos · ETA · alertas de demora · comunicación de estado", "例外关闭时间": "Tiempo de cierre de excepción", "加急补救成本": "Coste de recuperación urgente", "里程碑、ETA、延迟事件、客服与补救成本": "Hitos, ETA, eventos de demora, atención al cliente y costes de recuperación", "与 freight audit 组合形成“检测—决策—纠正—结算”的可验证闭环。": "Junto con la auditoría de flete, crea un ciclo verificable de detectar-decidir-corregir-liquidar.",
  "自有车队、设备与资产生产率": "Flota propia, equipos y productividad de activos", "在自有和外包运力之间优化车辆、司机、设备与回程资源。": "Optimice vehículos, conductores, equipos y retornos entre capacidad propia y subcontratada.", "自有/外包平衡 · 设备调配 · 空驶控制": "Equilibrio propio/subcontratado · posicionamiento de equipos · control de millas vacías", "空驶率": "Tasa de millas vacías", "自有车队利用率": "Utilización de flota propia", "设备周转": "Rotación de equipos", "车队状态、司机、设备、外包成本和线路": "Estado de flota, conductores, equipos, costes subcontratados y rutas", "仅在客户拥有或混合使用车队时进入正式价值范围。": "Entre al alcance formal solo si el cliente posee o utiliza una flota híbrida.",
  "网络决策、绩效洞察与持续改善": "Decisiones de red, información de desempeño y mejora continua", "用真实运营数据进行情景建模，把单次优化变成可持续的治理机制。": "Use datos operativos reales para modelar escenarios y convierta optimización puntual en un mecanismo de gobierno sostenible.", "情景建模 · 车道治理 · 根因洞察": "Modelado de escenarios · gobierno de rutas · análisis de causa raíz", "网络 Cost-to-Serve": "Cost-to-Serve de red", "计划/实际偏差": "Variación plan/real", "兑现率": "Tasa de realización", "历史运输、网络约束、成本、服务与情景参数": "Movimientos históricos, restricciones de red, coste, servicio y parámetros de escenario", "作为已验证执行价值之后的结构性扩展，而不是首期 ROI 的填充项。": "Es una extensión estructural tras valor de ejecución validado, no un relleno para el ROI inicial.",
  "合规、碳排与韧性": "Cumplimiento, carbono y resiliencia", "当客户议程覆盖跨境、ESG 或供应链风险时，才作为可选扩展领域。": "Úselo como extensión opcional solo cuando la agenda del cliente cubra riesgo transfronterizo, ESG o de cadena de suministro.", "排放分析 · 中断情景 · 文件完备性": "Análisis de emisiones · escenarios de interrupción · integridad documental", "CO₂e / 运量": "CO₂e / volumen", "合规事件": "Eventos de cumplimiento", "恢复时间": "Tiempo de recuperación", "排放、法规、事件、路线与业务连续性数据": "Datos de emisiones, regulaciones, eventos, rutas y continuidad de negocio", "需明确产品边界；跨境贸易深度合规不应默认归因于 OTM。": "Aclare límites de producto; el cumplimiento profundo de comercio transfronterizo no debe atribuirse a OTM por defecto.",
};

export const translate = (language: Language, text: string) => language === "zh" ? text : (language === "en" ? english[text] : spanish[text]) ?? text;
export const localeForLanguage = (language: Language) => language === "zh" ? "zh-CN" : language === "es" ? "es-ES" : "en-US";
