/* Design reminder: "决策档案室" — a workshop dossier that makes evidence maturity visible before financial value is asserted. */
import { useEffect, useMemo, useState } from "react";
import { useLanguage, type Language } from "@/contexts/LanguageContext";
import { gateDescription, isHardRoiGate, type EvidenceGate } from "@/lib/evidence";
import type { Driver } from "@/lib/oneOracleDrivers";
import "./layered-workflow.css";

type WorkflowProps = {
  drivers: Driver[];
  evidenceGates: Record<string, EvidenceGate>;
  onEvidenceGateChange: (driverId: string, gate: EvidenceGate) => void;
  brandMarkSrc: string;
  onSelectDriver: (id: string) => void;
  runwayFocus?: WorkflowFocus;
};

export type WorkflowFocus = "audit" | "visibility";
type Copy = { kicker: string; title: string; intro: string; layers: string[]; discovery: string; collaboration: string; evidence: string; executive: string; audit: string; visibility: string; focusCopy: string; gate: string; owner: string; period: string; scope: string; source: string; fallback: string; status: string; statusValues: string[]; required: string; hard: string; opportunity: string; next: string; exportReady: string; notReady: string; question: string; questions: string[] };

const COPY: Record<Language, Copy> = {
  zh: { kicker: "03.2 / assessment workflow", title: "先把问题与证据归档，再让 ROI 开始计算。", intro: "Discovery、客户协作、Evidence Gate 与 Executive 输出共用同一 driver ID。当前首期只聚焦 Freight Audit 与 Visibility；其他 One Oracle 能力保持为受控扩展。", layers: ["Discovery", "Customer collaboration", "ROI financial engine", "Executive output"], discovery: "Discovery Library", collaboration: "客户协作证据文件", evidence: "Evidence Gate", executive: "高管输出", audit: "Freight Audit", visibility: "Visibility", focusCopy: "选择一个首期 OTM 主题，按问题、数据和负责人推进；这里记录证据，不制造承诺。", gate: "证据门槛", owner: "数据负责人", period: "数据期间", scope: "范围", source: "来源", fallback: "替代方式", status: "收集状态", statusValues: ["未开始", "收集中", "待验证", "已验证"], required: "必需的数据文件", hard: "可进入 Base ROI", opportunity: "只作为机会范围", next: "下一步", exportReady: "可进入 Executive Output", notReady: "尚不能进入 Base ROI", question: "Discovery question", questions: ["当前 carrier invoice 是否 100% 审核、抽样审核，还是自动付款？", "重复账单、合同费率、燃油附加费和 accessorial 是否有历史发现或样本？", "运输里程碑、ETA 与延误例外是否能逐票追溯？", "谁确认加急、客服和计划团队因例外产生的可避免成本？"] },
  en: { kicker: "03.2 / assessment workflow", title: "File the questions and evidence before asking ROI to calculate.", intro: "Discovery, customer collaboration, evidence gates, and executive output share the same driver ID. Phase one focuses on Freight Audit and Visibility; other One Oracle capabilities remain controlled extensions.", layers: ["Discovery", "Customer collaboration", "ROI financial engine", "Executive output"], discovery: "Discovery Library", collaboration: "Customer collaboration evidence file", evidence: "Evidence Gate", executive: "Executive output", audit: "Freight Audit", visibility: "Visibility", focusCopy: "Choose a phase-one OTM topic and progress through questions, data, and owners. This workspace records evidence; it does not manufacture a commitment.", gate: "Evidence gate", owner: "Data owner", period: "Data period", scope: "Scope", source: "Source", fallback: "Fallback", status: "Collection status", statusValues: ["Not started", "In collection", "Awaiting validation", "Validated"], required: "Required evidence file", hard: "Eligible for Base ROI", opportunity: "Opportunity range only", next: "Next action", exportReady: "Eligible for Executive Output", notReady: "Not yet eligible for Base ROI", question: "Discovery question", questions: ["Are carrier invoices reviewed 100%, sampled, or released through straight-through payment today?", "Are historical duplicate, contracted-rate, fuel-surcharge, or accessorial findings available for review or sampling?", "Can shipment milestones, ETA, and delay exceptions be traced at shipment level?", "Who can validate avoidable expedite, customer-service, and planner cost triggered by exceptions?"] },
  es: { kicker: "03.2 / flujo de evaluación", title: "Archive las preguntas y la evidencia antes de pedir al ROI que calcule.", intro: "Discovery, colaboración con el cliente, evidencias y salida ejecutiva comparten el mismo ID de driver. La fase uno se centra en Freight Audit y Visibility; otras capacidades One Oracle quedan como extensiones controladas.", layers: ["Discovery", "Colaboración", "Motor financiero ROI", "Salida ejecutiva"], discovery: "Biblioteca Discovery", collaboration: "Archivo de evidencia del cliente", evidence: "Puerta de evidencia", executive: "Salida ejecutiva", audit: "Freight Audit", visibility: "Visibility", focusCopy: "Elija un tema OTM de fase uno y avance mediante preguntas, datos y responsables. Este espacio registra evidencia; no fabrica un compromiso.", gate: "Puerta de evidencia", owner: "Responsable de datos", period: "Periodo", scope: "Alcance", source: "Fuente", fallback: "Alternativa", status: "Estado de recopilación", statusValues: ["No iniciado", "En recopilación", "Pendiente de validar", "Validado"], required: "Archivo de evidencia requerido", hard: "Elegible para ROI base", opportunity: "Solo rango de oportunidad", next: "Siguiente acción", exportReady: "Elegible para salida ejecutiva", notReady: "Aún no elegible para ROI base", question: "Pregunta Discovery", questions: ["¿Las facturas de transporte se revisan al 100%, por muestra o se pagan automáticamente?", "¿Existen hallazgos históricos o muestras de duplicados, tarifas, combustible o accessorials?", "¿Se pueden rastrear hitos, ETA y excepciones de retraso por envío?", "¿Quién puede validar los costes evitables de urgencia, servicio y planificación causados por excepciones?"] },
};

const DISCOVERY_FIELDS = {
  audit: ["Annual carrier invoice count", "Total annual freight spend", "Invoice audit-process walkthrough", "Duplicate / rate / surcharge / accessorial history", "Third-party audit fee and scope"],
  visibility: ["Shipment milestone and ETA coverage", "Exception volume and closure time", "Manual status-check minutes", "Avoidable expedite / recovery cost", "Customer-service and planner ownership"],
};

export default function AssessmentWorkflow({ drivers, evidenceGates, onEvidenceGateChange, brandMarkSrc, onSelectDriver, runwayFocus }: WorkflowProps) {
  const { language } = useLanguage();
  const c = COPY[language];
  const [focus, setFocus] = useState<WorkflowFocus>("audit");
  const [collectionStatus, setCollectionStatus] = useState(c.statusValues[0]);
  const targetId = focus === "audit" ? "04" : "05";
  const target = drivers.find((driver) => driver.id === targetId);
  const gate = evidenceGates[targetId] ?? "E0";
  const hardEligible = isHardRoiGate(gate);
  const readiness = useMemo(() => ({ audited: evidenceGates["04"] ?? "E0", visible: evidenceGates["05"] ?? "E0" }), [evidenceGates]);

  useEffect(() => { if (runwayFocus) setFocus(runwayFocus); }, [runwayFocus]);

  return <section className="assessment-workflow section-wrap section-anchor" id="workflow">
    <div className="section-lead"><div><div className="eyebrow"><img src={brandMarkSrc} alt="" />{c.kicker}</div><h2 className="section-heading">{c.title}</h2></div><p className="section-intro">{c.intro}</p></div>
    <div className="workflow-rail" aria-label="Assessment workflow">{c.layers.map((layer, index) => <div className={`workflow-rail-step ${index === 0 ? "active" : ""}`} key={layer}><b>0{index + 1}</b><span>{layer}</span></div>)}</div>
    <div className="workflow-dossier">
      <div className="workflow-discovery" id="discovery-file"><div className="workflow-file-head"><img src={brandMarkSrc} alt="" /><span>DISCOVERY FILE / PHASE 01</span><b>{focus === "audit" ? "OTM-01" : "OTM-02"}</b></div><div className="workflow-focus-tabs"><button className={focus === "audit" ? "active" : ""} onClick={() => { setFocus("audit"); onSelectDriver("04"); }}>{c.audit}</button><button className={focus === "visibility" ? "active" : ""} onClick={() => { setFocus("visibility"); onSelectDriver("05"); }}>{c.visibility}</button></div><p>{c.focusCopy}</p><div className="workflow-questions"><span>{c.question}</span>{c.questions.slice(focus === "audit" ? 0 : 2, focus === "audit" ? 2 : 4).map((question, index) => <div key={question}><b>Q0{index + 1}</b><strong>{question}</strong></div>)}</div><button className="workflow-driver-link" onClick={() => onSelectDriver(targetId)}>{target?.title} <i>↗</i></button></div>
      <div className="workflow-collaboration"><div className="workflow-panel-label">02 / {c.collaboration}</div><h3>{c.required}</h3><div className="evidence-field-list">{DISCOVERY_FIELDS[focus].map((field, index) => <div className="evidence-field" key={field}><b>{String(index + 1).padStart(2, "0")}</b><span>{field}</span><i>{index < 2 ? c.owner : index === 2 ? c.period : c.scope}</i></div>)}</div><div className="workflow-record-grid"><label><span>{c.source}</span><input placeholder={language === "zh" ? "例如：AP、TMS 或客户工作簿" : "e.g., AP, TMS, or client workbook"} /></label><label><span>{c.status}</span><select value={collectionStatus} onChange={(event) => setCollectionStatus(event.target.value)}>{c.statusValues.map((status) => <option key={status}>{status}</option>)}</select></label><label><span>{c.fallback}</span><input placeholder={language === "zh" ? "样本、季度年化或待定" : "Sample, annualized quarter, or TBD"} /></label></div></div>
      <div className="workflow-gate" id="evidence-gate"><div className="workflow-panel-label">03 / {c.evidence}</div><h3>{gate} <span>{gateDescription[gate]}</span></h3><select value={gate} onChange={(event) => onEvidenceGateChange(targetId, event.target.value as EvidenceGate)}>{(["E0", "E1", "E2", "E3"] as EvidenceGate[]).map((item) => <option key={item} value={item}>{item} — {gateDescription[item]}</option>)}</select><div className={`workflow-gate-result ${hardEligible ? "ready" : "blocked"}`}><b>{hardEligible ? c.hard : c.opportunity}</b><span>{hardEligible ? c.exportReady : c.notReady}</span></div><div className="workflow-readiness"><span>OTM-01 / {readiness.audited}</span><span>OTM-02 / {readiness.visible}</span></div><p><strong>{c.next}:</strong> {hardEligible ? (language === "zh" ? "确认范围、币种、TCO 与重叠归属后，纳入 Executive Output。" : language === "es" ? "Confirme alcance, moneda, TCO y solapamiento antes de incluirlo en la salida ejecutiva." : "Confirm scope, currency, TCO, and overlap ownership before including it in Executive Output.") : (language === "zh" ? "完成客户基线与财务/业务负责人验证，再升级为 E2。" : language === "es" ? "Complete la línea base del cliente y la validación del responsable financiero/operativo antes de elevarlo a E2." : "Complete the customer baseline and finance/operational-owner validation before promoting to E2.")}</p></div>
    </div>
  </section>;
}
