/* Design reminder: “Decision Archive” — one customer question becomes one concrete team conversation, not an abstract recommendation. */
import { useEffect, useMemo, useState } from "react";
import { useLanguage, type Language } from "@/contexts/LanguageContext";
import "./layered-workflow.css";

type WorkflowFocus = "optimization" | "audit" | "visibility";
type Discussion = { caseItem: string; people: string; prompts: [string, string, string] };
type Topic = { tab: string; question: string; answers: [string, string]; next: [string, string]; discussion: [Discussion, Discussion] };
type Copy = { kicker: string; title: string; intro: string; choose: string; questionLabel: string; nextLabel: string; reset: string; briefTitle: string; caseLabel: string; peopleLabel: string; questionsLabel: string; copyBrief: string; copied: string; downloadBrief: string; deeper: string; topics: Record<WorkflowFocus, Topic> };
type WorkflowProps = { brandMarkSrc: string; runwayFocus?: WorkflowFocus; onOpenAdvanced?: () => void };

const COPY: Record<Language, Copy> = {
  zh: {
    kicker: "把问题想清楚", title: "选一件最想改善的事。", intro: "不需要先准备资料，也不需要算 ROI。选一个主题，回答一个问题，你就会得到一张可直接带给团队的讨论清单。", choose: "我想先弄清", questionLabel: "现在最关键的问题", nextLabel: "你的讨论清单", reset: "换一个问题", briefTitle: "这就是你下一次讨论要带走的东西。", caseLabel: "带来一个最近案例", peopleLabel: "找这两类同事", questionsLabel: "用这三个问题开始", copyBrief: "复制清单", copied: "已复制", downloadBrief: "下载清单", deeper: "继续深入查看", topics: {
      optimization: { tab: "计划与装载", question: "你能否看见订单、交期与路线如何被放进同一轮计划？", answers: ["大致能看见", "还看不见／不确定"], next: ["先从一条常跑线路开始，找出可以合并的订单和没有装满的装载。", "先弄清今天是谁、用什么方式把订单、交期和路线排在一起。"], discussion: [{ caseItem: "一条近期常跑线路，或一次没有装满的运输计划", people: "计划负责人 + 订单／客户服务同事", prompts: ["哪些订单本来可以合在一起？", "哪些装载没有装满，为什么？", "哪个限制最常导致临时改计划或加急？"] }, { caseItem: "一次最近发生临时改计划或加急的订单", people: "计划负责人 + 订单管理同事", prompts: ["订单、交期和路线今天分别在哪里看？", "谁决定把它们排进同一轮计划？", "什么信息缺失时最容易产生加急？"] }] },
      audit: { tab: "运费与发票", question: "你是否知道发票目前是怎样被审核的？", answers: ["有固定规则或审核流程", "不清楚／各团队做法不同"], next: ["用一张近期发票确认哪些费用会被核对，哪些可能直接通过。", "先把发票从收到到付款的实际过程画出来，再找最了解结算的人确认。"], discussion: [{ caseItem: "一张近期 carrier invoice，最好包含基本运费和附加费", people: "结算／财务同事 + 运输管理同事", prompts: ["这张发票上的哪些费用会被核对？", "合同费率或服务是否会被一起确认？", "发现不对时，谁负责处理和追回？"] }, { caseItem: "一张最近已付款的发票，或一次争议案例", people: "最了解结算流程的同事 + 财务同事", prompts: ["发票今天是全部审核、抽样审核，还是自动付款？", "每个团队分别做了什么？", "最容易漏掉或重复的费用在哪里？"] }] },
      visibility: { tab: "可视化与异常", question: "发生延误时，你能否知道哪一票受影响、该由谁处理？", answers: ["大致知道", "通常需要人工追问"], next: ["用一个最近的延误案例，回看什么时候发现、谁处理，以及有没有造成额外影响。", "先把一次延误从发现到处理的过程画出来，找出最需要人工追问的地方。"], discussion: [{ caseItem: "一个最近的延误或服务异常案例", people: "运输运营同事 + 客户服务或计划同事", prompts: ["什么时候发现异常？", "谁决定下一步并通知相关方？", "有没有产生加急、客户影响或额外沟通？"] }, { caseItem: "一次需要电话、邮件或聊天反复追问的运输事件", people: "负责运输追踪的同事 + 客户服务同事", prompts: ["最先从哪里知道发生了延误？", "需要问谁才能知道哪一票受影响？", "哪一步最值得先变得可见和可追溯？"] }] }
    }
  },
  en: {
    kicker: "make one question clear", title: "Choose the one thing you most want to improve.", intro: "You do not need to prepare information or calculate ROI first. Choose a topic, answer one question, and receive a discussion brief you can take to your team.", choose: "I want to clarify", questionLabel: "The key question now", nextLabel: "Your discussion brief", reset: "Choose another question", briefTitle: "Take these three things into your next conversation.", caseLabel: "Bring one recent example", peopleLabel: "Invite these people", questionsLabel: "Start with these questions", copyBrief: "Copy brief", copied: "Copied", downloadBrief: "Download brief", deeper: "Continue to the full toolkit", topics: {
      optimization: { tab: "Planning & loads", question: "Can you see how orders, delivery windows, and routes enter the same planning cycle?", answers: ["Mostly yes", "Not yet / not sure"], next: ["Start with one regular lane and identify orders that could travel together and loads that are not full.", "First clarify who and what process brings orders, delivery windows, and routes together today."], discussion: [{ caseItem: "One recent regular lane or an under-filled shipment plan", people: "A planning owner + an order or customer-service colleague", prompts: ["Which orders could have travelled together?", "Which loads were not full, and why?", "Which constraint most often causes plan changes or expedites?"] }, { caseItem: "One recent order that needed a plan change or expedite", people: "A planning owner + an order-management colleague", prompts: ["Where are orders, delivery windows, and routes viewed today?", "Who puts them into the same planning cycle?", "What missing information most often creates an expedite?"] }] },
      audit: { tab: "Freight & invoices", question: "Do you know how freight invoices are reviewed today?", answers: ["There is a consistent rule or process", "Not sure / teams work differently"], next: ["Use one recent invoice to confirm which charges are checked and which can pass directly.", "Map the actual path from an invoice arriving to payment, then confirm it with the colleague closest to settlement."], discussion: [{ caseItem: "One recent carrier invoice with base freight and accessorials if possible", people: "A settlement or finance colleague + a transport-management colleague", prompts: ["Which charges on this invoice are checked?", "Are contracted rates or service facts checked too?", "Who resolves and recovers an incorrect charge?"] }, { caseItem: "One recently paid invoice or one dispute case", people: "The colleague closest to settlement + a finance colleague", prompts: ["Are invoices fully reviewed, sampled, or paid automatically?", "What does each team do today?", "Where are duplicate or incorrect charges easiest to miss?"] }] },
      visibility: { tab: "Visibility & exceptions", question: "When a shipment is delayed, can you see which shipment is affected and who acts?", answers: ["Mostly yes", "We usually have to chase it manually"], next: ["Use one recent delay to review when it was found, who acted, and whether it caused extra impact.", "Map one delay from discovery to handling and identify where manual chasing is most necessary."], discussion: [{ caseItem: "One recent delay or service exception", people: "A transport-operations colleague + a customer-service or planning colleague", prompts: ["When was the exception discovered?", "Who decided the next action and notified others?", "Did it create expedite, customer impact, or extra communication?"] }, { caseItem: "One shipment event that required repeated calls, emails, or messages", people: "The person who tracks transport + a customer-service colleague", prompts: ["Where did you first learn there was a delay?", "Who had to be asked to identify the affected shipment?", "Which step should become visible and traceable first?"] }] }
    }
  },
  es: {
    kicker: "aclare una pregunta", title: "Elija lo que más quiere mejorar.", intro: "No necesita preparar información ni calcular ROI primero. Elija un tema, responda una pregunta y reciba un resumen para llevar a su equipo.", choose: "Quiero aclarar", questionLabel: "La pregunta clave ahora", nextLabel: "Su resumen de discusión", reset: "Elegir otra pregunta", briefTitle: "Lleve estas tres cosas a la próxima conversación.", caseLabel: "Traiga un ejemplo reciente", peopleLabel: "Invite a estas personas", questionsLabel: "Empiece con estas preguntas", copyBrief: "Copiar resumen", copied: "Copiado", downloadBrief: "Descargar resumen", deeper: "Continuar al kit completo", topics: {
      optimization: { tab: "Planificación y cargas", question: "¿Puede ver cómo pedidos, ventanas de entrega y rutas entran en el mismo ciclo de planificación?", answers: ["Más o menos sí", "Aún no / no estoy seguro"], next: ["Empiece con una ruta frecuente e identifique pedidos que podrían viajar juntos y cargas que no están completas.", "Primero aclare quién y qué proceso reúne hoy pedidos, ventanas de entrega y rutas."], discussion: [{ caseItem: "Una ruta frecuente reciente o un plan de envío con carga incompleta", people: "Responsable de planificación + colega de pedidos o servicio al cliente", prompts: ["¿Qué pedidos podrían haber viajado juntos?", "¿Qué cargas no estaban completas y por qué?", "¿Qué restricción causa más cambios de plan o urgencias?"] }, { caseItem: "Un pedido reciente que necesitó cambio de plan o urgencia", people: "Responsable de planificación + colega de gestión de pedidos", prompts: ["¿Dónde se ven hoy pedidos, ventanas y rutas?", "¿Quién los lleva al mismo ciclo de planificación?", "¿Qué información faltante crea más urgencias?"] }] },
      audit: { tab: "Flete y facturas", question: "¿Sabe cómo se revisan hoy las facturas de flete?", answers: ["Hay una regla o proceso consistente", "No estoy seguro / cada equipo trabaja distinto"], next: ["Use una factura reciente para confirmar qué cargos se revisan y cuáles pasan directamente.", "Dibuje el camino real desde que llega una factura hasta el pago y confírmelo con quien conoce la liquidación."], discussion: [{ caseItem: "Una factura reciente de carrier, con flete base y recargos si es posible", people: "Colega de liquidación o finanzas + colega de gestión de transporte", prompts: ["¿Qué cargos de esta factura se revisan?", "¿También se revisan tarifas contratadas o hechos del servicio?", "¿Quién resuelve y recupera un cargo incorrecto?"] }, { caseItem: "Una factura pagada recientemente o un caso de disputa", people: "La persona más cercana a la liquidación + un colega de finanzas", prompts: ["¿Se revisan todas las facturas, por muestra o se pagan automáticamente?", "¿Qué hace cada equipo hoy?", "¿Dónde es más fácil no detectar un cargo duplicado o incorrecto?"] }] },
      visibility: { tab: "Visibilidad y excepciones", question: "Cuando un envío se retrasa, ¿puede ver qué envío está afectado y quién actúa?", answers: ["Más o menos sí", "Normalmente hay que perseguirlo manualmente"], next: ["Use un retraso reciente para revisar cuándo se detectó, quién actuó y si causó impacto adicional.", "Dibuje un retraso desde la detección hasta la gestión e identifique dónde hace falta perseguir información."], discussion: [{ caseItem: "Un retraso reciente o una excepción de servicio", people: "Colega de operaciones de transporte + colega de servicio al cliente o planificación", prompts: ["¿Cuándo se detectó la excepción?", "¿Quién decidió la siguiente acción y avisó a los demás?", "¿Generó urgencia, impacto al cliente o comunicación adicional?"] }, { caseItem: "Un evento de envío que necesitó llamadas, correos o mensajes repetidos", people: "La persona que sigue el transporte + un colega de servicio al cliente", prompts: ["¿Dónde se enteraron primero del retraso?", "¿A quién hubo que preguntar para identificar el envío afectado?", "¿Qué paso debería ser visible y rastreable primero?"] }] }
    }
  }
};

export default function AssessmentWorkflow({ brandMarkSrc, runwayFocus, onOpenAdvanced }: WorkflowProps) {
  const { language } = useLanguage();
  const c = COPY[language];
  const [focus, setFocus] = useState<WorkflowFocus>("optimization");
  const [answer, setAnswer] = useState<number | null>(null);
  const [copied, setCopied] = useState(false);
  const topic = c.topics[focus];
  const discussion = answer === null ? null : topic.discussion[answer];
  const briefText = useMemo(() => discussion ? `${c.nextLabel}\n${topic.tab}\n\n${c.caseLabel}: ${discussion.caseItem}\n${c.peopleLabel}: ${discussion.people}\n\n${c.questionsLabel}:\n• ${discussion.prompts.join("\n• ")}\n\n${topic.next[answer ?? 0]}` : "", [answer, c, discussion, topic]);

  useEffect(() => { if (runwayFocus) { setFocus(runwayFocus); setAnswer(null); setCopied(false); } }, [runwayFocus]);
  const chooseTopic = (next: WorkflowFocus) => { setFocus(next); setAnswer(null); setCopied(false); };
  const persistBrief = () => { if (!discussion || answer === null) return; const entry = { topic: topic.tab, question: topic.question, answer: topic.answers[answer], discussion, savedAt: new Date().toISOString() }; try { const current = JSON.parse(localStorage.getItem("otm-team-discussion-briefs") ?? "[]"); localStorage.setItem("otm-team-discussion-briefs", JSON.stringify([entry, ...current].slice(0, 12))); } catch { localStorage.setItem("otm-team-discussion-briefs", JSON.stringify([entry])); } };
  const copyBrief = async () => { persistBrief(); try { await navigator.clipboard.writeText(briefText); setCopied(true); } catch { setCopied(true); } };
  const downloadBrief = () => { persistBrief(); const blob = new Blob([briefText], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `otm-team-discussion-${focus}.txt`; link.click(); URL.revokeObjectURL(url); };

  return <section className="assessment-workflow section-wrap section-anchor" id="workflow">
    <div className="section-lead"><div><div className="eyebrow"><img src={brandMarkSrc} alt="" />{c.kicker}</div><h2 className="section-heading">{c.title}</h2></div><p className="section-intro">{c.intro}</p></div>
    <div className="simple-workflow" id="discovery-file">
      <div className="simple-topic-panel"><span className="simple-label">{c.choose}</span><div className="simple-topic-tabs">{(Object.keys(c.topics) as WorkflowFocus[]).map((key) => <button key={key} className={focus === key ? "active" : ""} onClick={() => chooseTopic(key)}>{c.topics[key].tab}</button>)}</div><div className="simple-question"><span>{c.questionLabel}</span><h3>{topic.question}</h3><div className="simple-answer-grid">{topic.answers.map((item, index) => <button key={item} className={answer === index ? "selected" : ""} onClick={() => { setAnswer(index); setCopied(false); }}><i>{answer === index ? "✓" : ""}</i>{item}</button>)}</div></div></div>
      <div className="simple-next-panel" id="evidence-gate"><span className="simple-label">{c.nextLabel}</span>{!discussion ? <div className="simple-empty"><p>←</p><strong>{language === "zh" ? "先选一个答案。" : language === "es" ? "Elija una respuesta primero." : "Choose one answer first."}</strong><span>{language === "zh" ? "系统会把复杂的下一步，变成一张可以带给团队的讨论清单。" : language === "es" ? "Convertiremos el siguiente paso complejo en un resumen que puede llevar a su equipo." : "We will turn the complex next step into a brief you can take to your team."}</span></div> : <div className="simple-brief"><div className="simple-result-mark">→</div><h3>{c.briefTitle}</h3><div className="simple-brief-item"><span>{c.caseLabel}</span><strong>{discussion.caseItem}</strong></div><div className="simple-brief-item"><span>{c.peopleLabel}</span><strong>{discussion.people}</strong></div><div className="simple-brief-item"><span>{c.questionsLabel}</span><ol>{discussion.prompts.map((prompt) => <li key={prompt}>{prompt}</li>)}</ol></div><p className="simple-brief-next">{topic.next[answer ?? 0]}</p><div className="simple-brief-actions"><button className="simple-save" onClick={() => void copyBrief()}>{copied ? c.copied : c.copyBrief}</button><button className="simple-download" onClick={downloadBrief}>{c.downloadBrief}</button></div><button className="simple-deeper" onClick={onOpenAdvanced}>{c.deeper} <span>↗</span></button><button className="simple-reset" onClick={() => { setAnswer(null); setCopied(false); }}>{c.reset}</button></div>}</div>
    </div>
  </section>;
}
