/* Design reminder: “Decision Archive Assessment Runway” — a customer-owned task path inside the evidence archive. Warm ivory, charcoal, and archive vermilion only; make the user's next move obvious without turning the workbench into a generic dashboard. */
import { useState } from "react";
import { ArrowRight, FileCheck2, LockKeyhole, MapPinned, Scale, Sparkles } from "lucide-react";
import { type Language } from "@/contexts/LanguageContext";
import { gateDescription, isHardRoiGate, type EvidenceGate } from "@/lib/evidence";
import type { Driver } from "@/lib/oneOracleDrivers";
import FreightAuditTask from "./FreightAuditTask";
import GtmTriggeredModules from "./GtmTriggeredModules";
import ShipmentOptimizationTask from "./ShipmentOptimizationTask";
import "./assessment-runway.css";

export type RunwayPath = "optimization" | "audit" | "visibility" | "broader";
export type RunwayStage = "problem" | "driver" | "discovery" | "evidence" | "roi" | "output";

type PathOption = { id: RunwayPath; driverId: string; eyebrow: string; title: string; copy: string; cue: string; task: string; input: string; output: string };
type RunwayCopy = {
  eyebrow: string; title: string; intro: string; pathLabel: string; choose: string; current: string; nextLabel: string; resultLabel: string;
  stageLabels: [string, string, string, string, string, string]; stageOutputs: [string, string, string, string, string, string];
  nextChoose: string; nextDriver: string; nextDiscovery: string; nextEvidence: string; nextEvidenceLocked: string; nextRoi: string; nextOutput: string;
  actionDriver: string; actionDiscovery: string; actionEvidence: string; actionRoi: string; actionOutput: string;
  noPathTitle: string; noPathCopy: string; gateOpen: string; gateLocked: string; broaderNote: string; fieldNote: string; taskLabel: string; inputLabel: string; outputLabel: string; paths: PathOption[];
};

const COPY: Record<Language, RunwayCopy> = {
  zh: {
    eyebrow: "00 / Assessment Runway", title: "从你的运营问题，找到下一步。", intro: "先选现在最困扰你的一个运输问题。系统会把问题、需要了解的资料和下一步行动放在同一条路径上。", pathLabel: "选择你想先理清的事", choose: "选择这条路径", current: "你正在探索", nextLabel: "下一步建议", resultLabel: "你会得到",
    stageLabels: ["你的问题", "相关能力", "资料线索", "确认程度", "价值估算", "讨论摘要"], stageOutputs: ["一个清楚的运营问题", "一个相关的起始能力", "问题、资料与同事", "资料准备程度", "仅在资料足够时", "带给你团队的摘要"],
    nextChoose: "先选一个现在最困扰你的运输或贸易问题。", nextDriver: "看看这项能力如何回应你的问题，以及可以从哪些资料开始确认。", nextDiscovery: "整理你已有的资料线索，并找出最了解流程和数据的同事。", nextEvidence: "看看现有资料能支持到哪一步；这不是购买决定，也不要求你现在计算 ROI。", nextEvidenceLocked: "资料还不足以支持金额估算；先确认基线和能核实它的同事。", nextRoi: "资料已足够形成初步估算。现在可以尝试把它带进价值估算工作区。", nextOutput: "当价值和成本假设准备好后，生成一份可带去内部讨论的摘要。",
    actionDriver: "看看这项能力", actionDiscovery: "整理我的资料线索", actionEvidence: "查看资料准备度", actionRoi: "试算潜在价值", actionOutput: "生成讨论摘要",
    noPathTitle: "从一个你自己的真实问题开始", noPathCopy: "选择现在最想弄清的一件事。系统不会默认把所有能力、地区或价值都塞进同一个结论。", gateOpen: "可以尝试价值估算", gateLocked: "先整理线索", broaderNote: "这条路径会打开完整 Value Library，帮助你先定位最相关的一项能力。", fieldNote: "问题越具体，下一步越清楚。", taskLabel: "现在可以做什么", inputLabel: "你需要", outputLabel: "你会得到", paths: [
      { id: "optimization", driverId: "01", eyebrow: "OTM / 01", title: "运输计划与装载优化", copy: "你想让订单合并得更好、装载更满、路线和服务选择更合理，并减少临时改计划与加急。", cue: "准备我的计划与装载优化讨论", task: "准备一次运输计划与装载优化内部讨论", input: "一个计划问题、三类计划资料、几位了解情况的同事", output: "可复制或下载的 45 分钟讨论清单" },
      { id: "audit", driverId: "04", eyebrow: "OTM / 04", title: "运费、发票与结算完整性", copy: "你正在遇到发票错误、重复付款、费率偏差，或不清楚是否已经充分审核。", cue: "准备我的内部讨论", task: "准备一次 Freight Audit 内部讨论", input: "一个具体问题、三类资料、几位了解情况的同事", output: "可复制或下载的 45 分钟讨论清单" },
      { id: "visibility", driverId: "05", eyebrow: "OTM / 05", title: "可视化、异常与服务保障", copy: "你正在遇到运输不可视、状态查询、人工追踪、延误或加急。", cue: "梳理可视化问题", task: "梳理你想改善的异常或状态问题", input: "一个异常场景、状态线索、相关同事", output: "清晰的探索起点与资料清单" },
      { id: "broader", driverId: "01", eyebrow: "ONE ORACLE", title: "其他运输或贸易问题", copy: "你想弄清规划、承运商、网络、车队、合规或全球贸易中的某个问题。", cue: "定位相关能力", task: "先定位一项相关 Value Driver", input: "一条你想改善的运营问题", output: "相关能力说明与下一步探索" },
    ],
  },
  en: {
    eyebrow: "00 / Assessment Runway", title: "Start with your operating question. Find your next step.", intro: "Choose the one transport issue that is most difficult for you right now. This route puts the question, the information to find, and the next action in one place.", pathLabel: "Choose what you want to clarify first", choose: "Choose this path", current: "You are exploring", nextLabel: "Suggested next step", resultLabel: "You get",
    stageLabels: ["Your question", "Relevant capability", "Information trail", "Readiness", "Value estimate", "Discussion brief"], stageOutputs: ["A clear operating question", "A relevant starting capability", "Questions, information, colleagues", "Information readiness", "Only when evidence is sufficient", "A brief for your team"],
    nextChoose: "Choose the transport or trade issue you most want to clarify now.", nextDriver: "See how this capability could address your issue and what information can help you confirm it.", nextDiscovery: "Organise the information you already have and identify colleagues who know the process and data.", nextEvidence: "See what your current information can support. This is not a buying decision and it does not require an ROI today.", nextEvidenceLocked: "Your information is not yet sufficient for a value estimate. Confirm the baseline and the colleague who can verify it first.", nextRoi: "Your information is sufficient for an early estimate. You can now try it in the value workspace.", nextOutput: "When value and cost assumptions are ready, create a brief for your internal discussion.",
    actionDriver: "See this capability", actionDiscovery: "Organise my information", actionEvidence: "Check my readiness", actionRoi: "Estimate potential value", actionOutput: "Create discussion brief",
    noPathTitle: "Start with one real issue in your operation", noPathCopy: "Choose the one thing you most want to understand. The route will not force every capability, geography, or value claim into the same conclusion.", gateOpen: "Ready to try a value estimate", gateLocked: "Organise information first", broaderNote: "This path opens the full Value Library to help you locate the capability that is most relevant to your issue.", fieldNote: "A more specific question creates a clearer next step.", taskLabel: "DO THIS NOW", inputLabel: "YOU NEED", outputLabel: "YOU GET", paths: [
      { id: "optimization", driverId: "01", eyebrow: "OTM / 01", title: "Shipment Optimization", copy: "You want to consolidate orders better, fill loads more fully, make stronger route and service choices, and reduce plan changes or expedites.", cue: "Prepare my optimization discussion", task: "Prepare a Shipment Optimization internal discussion", input: "One planning issue, three planning information items, and colleagues who know the situation", output: "A copyable or downloadable 45-minute discussion brief" },
      { id: "audit", driverId: "04", eyebrow: "OTM / 04", title: "Freight spend, invoices and settlement", copy: "You may be seeing invoice errors, duplicate payment, rate variance, or uncertainty about audit coverage.", cue: "Prepare my internal discussion", task: "Prepare a Freight Audit internal discussion", input: "One concrete issue, three information items, and colleagues who know the situation", output: "A copyable or downloadable 45-minute discussion brief" },
      { id: "visibility", driverId: "05", eyebrow: "OTM / 05", title: "Visibility, exceptions and service assurance", copy: "You may be dealing with limited visibility, status checking, manual tracking, delays, or expedites.", cue: "Clarify my visibility issue", task: "Clarify the exception or status issue you want to improve", input: "One exception scenario, a status trail, and relevant colleagues", output: "A clear exploration start and information list" },
      { id: "broader", driverId: "01", eyebrow: "ONE ORACLE", title: "Another transport or trade question", copy: "You want to clarify an issue involving planning, carriers, network, fleet, compliance, or global trade.", cue: "Locate a relevant capability", task: "First locate one relevant value driver", input: "One operating issue you want to improve", output: "A relevant capability explanation and next exploration step" },
    ],
  },
  es: {
    eyebrow: "00 / Assessment Runway", title: "Empiece con su pregunta operativa. Encuentre su siguiente paso.", intro: "Elija el problema de transporte que más le preocupa ahora. Esta ruta reúne la pregunta, la información que debe localizar y el siguiente paso.", pathLabel: "Elija lo que quiere aclarar primero", choose: "Elegir esta ruta", current: "Está explorando", nextLabel: "Siguiente paso sugerido", resultLabel: "Obtiene",
    stageLabels: ["Su pregunta", "Capacidad relevante", "Rastro de información", "Preparación", "Estimación de valor", "Resumen de discusión"], stageOutputs: ["Una pregunta operativa clara", "Una capacidad inicial relevante", "Preguntas, información, colegas", "Preparación de la información", "Solo con evidencia suficiente", "Un resumen para su equipo"],
    nextChoose: "Elija el problema de transporte o comercio que más quiere aclarar ahora.", nextDriver: "Vea cómo esta capacidad puede responder a su problema y qué información puede ayudarle a confirmarlo.", nextDiscovery: "Organice la información que ya tiene e identifique a los colegas que conocen el proceso y los datos.", nextEvidence: "Vea lo que su información actual puede respaldar. No es una decisión de compra y no exige calcular ROI hoy.", nextEvidenceLocked: "Su información todavía no alcanza para una estimación de valor. Confirme primero la línea base y el colega que puede validarla.", nextRoi: "Su información permite una estimación inicial. Ahora puede probarla en el espacio de valor.", nextOutput: "Cuando estén listos los supuestos de valor y coste, cree un resumen para su discusión interna.",
    actionDriver: "Ver esta capacidad", actionDiscovery: "Organizar mi información", actionEvidence: "Revisar mi preparación", actionRoi: "Estimar valor potencial", actionOutput: "Crear resumen de discusión",
    noPathTitle: "Empiece con un problema real de su operación", noPathCopy: "Elija lo que más quiere entender. La ruta no pondrá por defecto cada capacidad, geografía o afirmación de valor en una sola conclusión.", gateOpen: "Puede probar una estimación de valor", gateLocked: "Organice la información primero", broaderNote: "Esta ruta abre la biblioteca de valor completa para ayudarle a ubicar la capacidad más relevante para su problema.", fieldNote: "Una pregunta más específica crea un siguiente paso más claro.", taskLabel: "HAGA ESTO AHORA", inputLabel: "NECESITA", outputLabel: "OBTIENE", paths: [
      { id: "optimization", driverId: "01", eyebrow: "OTM / 01", title: "Shipment Optimization", copy: "Quiere consolidar mejor los pedidos, llenar más las cargas, mejorar decisiones de ruta y servicio, y reducir cambios de plan o urgencias.", cue: "Preparar mi discusión de optimización", task: "Preparar una discusión interna de Shipment Optimization", input: "Un problema de planificación, tres fuentes de información y colegas que conocen la situación", output: "Un resumen de discusión de 45 minutos para copiar o descargar" },
      { id: "audit", driverId: "04", eyebrow: "OTM / 04", title: "Gasto de flete, facturas y liquidación", copy: "Puede estar viendo errores de factura, pagos duplicados, variación de tarifa o dudas sobre la cobertura de auditoría.", cue: "Preparar mi discusión interna", task: "Preparar una discusión interna de Freight Audit", input: "Un problema concreto, tres fuentes de información y colegas que conocen la situación", output: "Un resumen de discusión de 45 minutos para copiar o descargar" },
      { id: "visibility", driverId: "05", eyebrow: "OTM / 05", title: "Visibilidad, excepciones y servicio", copy: "Puede estar enfrentando poca visibilidad, consultas de estado, seguimiento manual, retrasos o urgencias.", cue: "Aclarar mi problema de visibilidad", task: "Aclarar el problema de excepción o estado que quiere mejorar", input: "Un escenario de excepción, un rastro de estado y colegas relevantes", output: "Un inicio claro de exploración y lista de información" },
      { id: "broader", driverId: "01", eyebrow: "ONE ORACLE", title: "Otra pregunta de transporte o comercio", copy: "Quiere aclarar un problema de planificación, carriers, red, flota, cumplimiento o comercio global.", cue: "Ubicar una capacidad relevante", task: "Primero ubique un driver de valor relevante", input: "Un problema operativo que quiere mejorar", output: "Una explicación de capacidad relevante y siguiente paso" },
    ],
  },
};

type Props = { language: Language; path: RunwayPath | null; stage: RunwayStage; selectedDriver: Driver; evidenceGate: EvidenceGate; onChoosePath: (path: RunwayPath) => void; onOpenGtmModule: (driverId: string) => void; onGoToDriver: () => void; onGoToDiscovery: () => void; onGoToEvidence: () => void; onGoToRoi: () => void; onGoToOutput: () => void };
const STAGES: RunwayStage[] = ["problem", "driver", "discovery", "evidence", "roi", "output"];

export default function AssessmentRunway({ language, path, stage, selectedDriver, evidenceGate, onChoosePath, onOpenGtmModule, onGoToDriver, onGoToDiscovery, onGoToEvidence, onGoToRoi, onGoToOutput }: Props) {
  const c = COPY[language];
  const [taskOpen, setTaskOpen] = useState<"optimization" | "audit" | "broader" | null>(null);
  const activeIndex = STAGES.indexOf(stage);
  const hardEligible = isHardRoiGate(evidenceGate);
  const selectedPath = c.paths.find((item) => item.id === path) ?? null;
  const isBroader = path === "broader";
  const next = !path ? { copy: c.nextChoose, label: c.choose, action: undefined, locked: false } : stage === "driver" ? { copy: c.nextDriver, label: c.actionDriver, action: onGoToDriver, locked: false } : stage === "discovery" ? { copy: c.nextDiscovery, label: c.actionDiscovery, action: onGoToDiscovery, locked: false } : stage === "evidence" && !hardEligible ? { copy: c.nextEvidenceLocked, label: c.actionEvidence, action: onGoToEvidence, locked: true } : stage === "evidence" ? { copy: c.nextRoi, label: c.actionRoi, action: onGoToRoi, locked: false } : stage === "roi" ? { copy: c.nextOutput, label: c.actionOutput, action: onGoToOutput, locked: false } : { copy: c.nextOutput, label: c.actionOutput, action: onGoToOutput, locked: false };
  const chooseTask = (nextPath: RunwayPath) => { onChoosePath(nextPath); const task = nextPath === "optimization" || nextPath === "audit" || nextPath === "broader" ? nextPath : null; setTaskOpen(task); if (task) window.setTimeout(() => document.getElementById(task === "optimization" ? "shipment-optimization-task" : task === "audit" ? "freight-audit-task" : "gtm-trigger")?.scrollIntoView({ behavior: "smooth", block: "start" }), 10); };

  return <section className="assessment-runway section-wrap section-anchor" id="assessment-runway">
    <div className="runway-heading"><div><div className="eyebrow"><span className="runway-eyebrow-mark" aria-hidden="true" /><span>{c.eyebrow}</span></div><h2>{c.title}</h2></div><p>{c.intro}</p></div>
    <div className="runway-problem-zone"><div className="runway-zone-label"><span>{c.pathLabel}</span><i /></div><div className="runway-path-cards">{c.paths.map((option) => <button key={option.id} type="button" className={`runway-path-card ${path === option.id ? "active" : ""}`} onClick={() => chooseTask(option.id)} aria-pressed={path === option.id}><span className="runway-path-code">{option.eyebrow}</span><h3>{option.title}</h3><p>{option.copy}</p><div className="runway-task-preview"><span>{c.taskLabel}</span><strong>{option.task}</strong><em>{c.inputLabel}: {option.input}</em><em>{c.outputLabel}: {option.output}</em></div><div><span>{path === option.id ? c.current : option.cue}</span><ArrowRight size={16} strokeWidth={1.8} /></div></button>)}</div></div>
    {taskOpen === "optimization" && path === "optimization" ? <ShipmentOptimizationTask language={language} onOpenDiscovery={onGoToDiscovery} /> : taskOpen === "audit" && path === "audit" ? <FreightAuditTask language={language} onOpenDiscovery={onGoToDiscovery} /> : taskOpen === "broader" && path === "broader" ? <GtmTriggeredModules language={language} onOpenModule={onOpenGtmModule} /> : <><div className="runway-track" aria-label="Assessment Runway">{STAGES.map((key, index) => <button type="button" key={key} className={`runway-step ${index < activeIndex ? "done" : ""} ${index === activeIndex ? "active" : ""} ${index > activeIndex ? "pending" : ""} ${key === "roi" && !hardEligible ? "locked" : ""}`} onClick={key === "driver" ? onGoToDriver : key === "discovery" ? onGoToDiscovery : key === "evidence" ? onGoToEvidence : key === "roi" && hardEligible ? onGoToRoi : key === "output" ? onGoToOutput : undefined} disabled={key === "roi" && !hardEligible}><span className="runway-step-dot">{index < activeIndex ? <FileCheck2 size={13} strokeWidth={2.1} /> : index === activeIndex ? <MapPinned size={13} strokeWidth={2.1} /> : key === "roi" && !hardEligible ? <LockKeyhole size={12} strokeWidth={2.1} /> : String(index + 1).padStart(2, "0")}</span><strong>{c.stageLabels[index]}</strong><em>{c.stageOutputs[index]}</em></button>)}</div><div className="runway-next-card"><div className="runway-next-icon" aria-hidden="true">{!path ? <Sparkles size={21} strokeWidth={1.6} /> : stage === "evidence" ? <Scale size={21} strokeWidth={1.6} /> : <ArrowRight size={21} strokeWidth={1.6} />}</div><div className="runway-next-copy"><span>{c.nextLabel}</span><h3>{next.copy}</h3>{selectedPath && <p>{isBroader ? c.broaderNote : `${c.current}: ${selectedDriver.title} · ${evidenceGate} — ${gateDescription[evidenceGate]}`}</p>}</div>{next.action ? <button type="button" className={`runway-next-action ${next.locked ? "locked" : ""}`} onClick={next.action}><span>{next.label}</span><ArrowRight size={17} strokeWidth={1.9} /></button> : <div className="runway-select-hint"><span>{c.noPathTitle}</span><p>{c.noPathCopy}</p></div>}</div>{path && <div className={`runway-gate-strip ${hardEligible ? "open" : "locked"}`}><span>{hardEligible ? c.gateOpen : c.gateLocked}</span><i /><b>{evidenceGate} — {gateDescription[evidenceGate]}</b><em>{c.fieldNote}</em></div>}</>}
  </section>;
}
